# fixed version at end 2024 siutation but with coastal-dynamics v1.0
name: coastalcodebook
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version, pip, and other very generic libraries
  - python=3.13.1
  - jupyterlab=4.3.4
  - pip=24.3.1
  - jupyter-book=1.0.4
  - pip:
      - coastal-dynamics==1.0.0
      - uptide==1.1
      - utide==0.3.0
      - numpy==2.2.1
      - pandas==2.2.3
      - pooch==1.8.2
      - geopandas==1.0.1
      - panel==1.5.5
      - bokeh==3.6.2
      - colorcet==3.1.0
      - holoviews==1.20.0
      - hvplot==0.11.2
      - ipykernel==6.29.5
      - adlfs==2024.12.0
      - dask[dataframe]==2024.12.1
      - jupyter-bokeh==4.0.5
      - cartopy==0.24.1
      - geoviews==1.14.0
      - scipy==1.14.1
      - python-dotenv==1.0.1
      - pre-commit==4.0.1
