name: coastalcodebook
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version, pip, and other very generic libraries
  - python=3.13.3
  - jupyterlab=4.4.2
  - pip=25.1.1
  - pip:
      - coastal-dynamics==1.0.0
      - uptide==1.1
      - utide==0.3.1
      - numpy==2.2.5
      - pandas==2.2.3
      - pooch==1.8.2
      - geopandas==1.0.1
      - panel==1.6.3
      - bokeh==3.7.2
      - colorcet==3.1.0
      - holoviews==1.20.2
      - hvplot==0.11.3
# In the exported environment the ipykernel version is in the dependencies, check
      - ipykernel==6.29
      - adlfs==2024.12.0
      - dask==2025.4.1
# dask[dataframe] is not in the exported environment. Should it not get a version number or the version of dask?
      - dask[dataframe]
      - jupyter-bokeh==4.0.5
      - cartopy==0.24.1
      - geoviews==1.14.0
      - scipy==1.15.2
      - python-dotenv==1.1.0
      - pre-commit==4.2.0
