#!/usr/bin/env bash

rsync -r --del "./questions/hashed_questions/" "/var/hashed_questions/"

mkdir "/etc/skel/questions"
ln -s "/var/hashed_questions/" "/etc/skel/questions"
ln -s "/var/database/" "/etc/skel"
rsync -r --del "./modules/" "/etc/skel/modules/"
rsync -r --del "./images/" "/etc/skel/images/"

users=$(getent passwd | grep "jupyter-" | cut -d: -f1)

for user in $users
do
  mkdir "/home/$user/questions"
  ln -s "/var/hashed_questions/" "/home/$user/questions"
  ln -s "/var/database/" "/home/$user"
  rsync -r --del "./modules/" "/home/$user/modules/"
  rsync -r --del "./images/" "/home/$user/images/"
done

