#!/usr/bin/env bash

mkdir /var/codebook
rsync -r --del "./hashed_questions/" "/var/codebook/hashed_questions/"
rsync -r --del "./modules/" "/var/codebook/modules/"
rsync -r --del "./images/" "/var/codebook/images/"

ln -s "/var/codebook/hashed_questions/" "/etc/skel"
ln -s "/var/codebook/database/" "/etc/skel"
ln -s "/var/codebook/modules/" "/etc/skel"
ln -s "/var/codebook/images/" "/etc/skel"

users=$(getent passwd | grep "jupyter-" | cut -d: -f1)

for user in $users
do
  ln -s "/var/codebook/hashed_questions/" "/home/$user"
  ln -s "/var/codebook/database/" "/home/$user"
  ln -s "/var/codebook/modules/" "/home/$user"
  ln -s "/var/codebook/images/" "/home/$user"
done

