name: Deploy JupyterBook to GitHub pages

on:
  push:
    branches: [main]
    paths:
      - "notebooks/**"
      - "book/**"
      - "environment.yml"
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  BuildBook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      # Step to activate the environment and install the kernel with the name "coastal-env"
      - name: Install Jupyter Kernel for CI
        run: |
          python -m ipykernel install --user --name conda-env-coastal-py --display-name "conda-env-coastal-py"

      # Copy notebooks to book notebooks directory
      - name: Copy hashed questions
        run: |
          rsync -av --delete hashed_questions/ book/hashed_questions/

      # Copy notebooks to book notebooks directory
      - name: Prepare notebooks for book
        run: |
          rsync -av --delete notebooks/ book/notebooks/

      # Build the JupyterBook
      - name: Build JupyterBook
        run: |
          jupyter-book build book/

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "book/_build/html"

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
